### PR TITLE
github: fix a mergify rule that was invalid

### PR DESCRIPTION
**Pull request by phlogistonjohn**
When converting the mergify yaml to match the new matrix rules in github workflow yaml, I added `build-nightly-server (opensuse, amd64)` but that's not a valid rule. Remove them.

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
Adding priority-review label as this error is blocking mergify from working.

**Review by obnoxxx — CHANGES_REQUESTED** [review]
I think `build-nightly-server` is not entirely invalid but for opensuse it is. I suggest to adjust the commit message wording. looks good otherwise!

**Review by obnoxxx — APPROVED** [review]
LGTM, thanks!

**Comment by obnoxxx** [comment]
@mergifyio refresh

**Pull request merged**
