### PR TITLE
Add kubernetes tests for the ad-server deployment

### PR DESCRIPTION
**Pull request by obnoxxx**
This PR adds kubernetes tests using k3d.
Based on PR #32 .

### CODE REVIEW

**Comment by obnoxxx** [comment]
So the k3d test actually works!
The k3s test does not work really - it fails to pull the image.
Just need to refine the test itself to have it show up.

**Comment by obnoxxx** [comment]
Now we have a "real" kubernetes level test for the AD container that actually works - see the "test-k3d" check!

@phlogistonjohn - what do you think?

**Comment by obnoxxx** [comment]
rebased after #32 merged

**Comment by obnoxxx** [comment]
rebased after #35 merged

**Comment by phlogistonjohn** [comment]
Looks generally good to me. You still have it as a draft though, so I am unsure if you're planning on making more changes.

**Comment by obnoxxx** [comment]
@phlogistonjohn removing draft status.
Should we change the name of the test from `test-k3d`? E.g. `test-ad-server-kubernetes`?

**Comment by obnoxxx** [comment]
> @phlogistonjohn removing draft status.
> Should we change the name of the test from `test-k3d`? E.g. `test-ad-server-kubernetes`?

Changed the test name.
Removed draft status.

**Review by phlogistonjohn — APPROVED** [review]
Looks like a good start to me!

**Pull request merged**
