### PR TITLE
samba toolbox

### PR DESCRIPTION
**Pull request by synarete**
Create dedicate image for developer's or power-user admin and testing operations. Similar to rook's toolbox.

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]
LGTM.

I'll leave it open a couple of days for others to take a look. Feel free to merge by Thursday if you don't get any other feedback.

**Review by anoopcs9 — COMMENTED** [review]
Should we then keep `samba-client` image as a separate one? How about renaming the current `samba-client` container?

**Comment by synarete** [comment]
> Should we then keep `samba-client` image as a separate one? How about renaming the current `samba-client` container?

This was an option we considered, but decided it would be better to leave `samba-client` a minimal image and have separate `samba-toolbox`, which most likely will add more and more debug packages over time (as needed).

**Comment by anoopcs9** [comment]
> > Should we then keep `samba-client` image as a separate one? How about renaming the current `samba-client` container?
> 
> This was an option we considered, but decided it would be better to leave `samba-client` a minimal image and have separate `samba-toolbox`, which most likely will add more and more debug packages over time (as needed).

Just now happened to notice the discussion from https://github.com/samba-in-kubernetes/samba-container/pull/83. Installing `samba-test` must be pulling more dependencies than `samba-client`. I liked the _toolbox_ suffix which can hold `samba-client` too. Considering the very low(or none) consumption of `samba-client` outside our testing infrastructure I am slightly more inclined to include `samba-test` and thereby rename the current image.

Sorry for the late noise.

**Comment by synarete** [comment]
> > > Should we then keep `samba-client` image as a separate one? How about renaming the current `samba-client` container?
> > 
> > 
> > This was an option we considered, but decided it would be better to leave `samba-client` a minimal image and have separate `samba-toolbox`, which most likely will add more and more debug packages over time (as needed).
> 
> Just now happened to notice the discussion from #83. Installing `samba-test` must be pulling more dependencies than `samba-client`. I liked the _toolbox_ suffix which can hold `samba-client` too. Considering the very low(or none) consumption of `samba-client` outside our testing infrastructure I am slightly more inclined to include `samba-test` and thereby rename the current image.
> 
> Sorry for the late noise.

That is also a valid option (thou it would require also a change in places which currently use samba-client image).
@phlogistonjohn What do you think?

**Comment by phlogistonjohn** [comment]
In quite a few cases I like the "fake it till you make it" approach unless there is a significant maintenance burden. In this cases "faking it" means we act like we have external users consuming samba-client. Adding `samba-test` or `samba-toolbox` means we don't disrupt our imaginary samba-client users with lots of extra stuff in the image. We could even choose to make samba-client a lower layer in the image - if the base distros align.  I'm not adamant about keeping samba-client but that's my current preference.

**Review by obnoxxx — APPROVED** [review]
since this has been agreed upon in principle in the discussions, I am approving. lgtm!

**Pull request merged**
