### PR TITLE
Enable creation of CentOS based AD server images with nightly builds of Samba

### PR DESCRIPTION
**Pull request by anoopcs9**

### CODE REVIEW

**Comment by anoopcs9** [comment]
@Mergifyio rebase

**Comment by anoopcs9** [comment]
combined

**build-nightly-ad-server (centos, amd64)** and **test-nightly-ad-server-kubernetes (centos, amd64)** are the new ones.

**Comment by obnoxxx** [comment]
@anoopcs9  why has this been moved out of draft status but labeled `do-not-merge`?

**Comment by anoopcs9** [comment]
> @anoopcs9 why has this been moved out of draft status but labeled `do-not-merge`?

I forgot to remove the label 😄

**Comment by obnoxxx** [comment]
@mergifyio rebase

**Review by obnoxxx — CHANGES_REQUESTED** [review]
Thanks for the PR, @anoopcs9  ! it generally looks good to me, but the test-nightly-ad-server-kubernetes job for centos is failingf with `Container image "samba-ad-server:centos-nightly" is not present with pull policy of Never` - some fix is needed.

**Comment by anoopcs9** [comment]
> Thanks for the PR, @anoopcs9 ! it generally looks good to me, but the test-nightly-ad-server-kubernetes job for centos is failingf with `Container image "samba-ad-server:centos-nightly" is not present with pull policy of Never` - some fix is needed.

It was a spurious failure.

**Review by phlogistonjohn — APPROVED** [review]
LGTM, thanks!

**Review by obnoxxx — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
