### PR TITLE
images: bump base image to fedora36

### PR DESCRIPTION
**Pull request by synarete**
Expects Fedora36 to be maintained until mid 2023.

Signed-off-by: Shachar Sharon <ssharon@redhat.com>

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]
LGTM, thanks!

**Comment by synarete** [comment]
> LGTM, thanks!

I tried to make it with `centos:stream9` but failed, even with `epel` repo enabled. Fallback to `fedora36`.

**Comment by phlogistonjohn** [comment]
> I tried to make it with centos:stream9 but failed, even with epel repo enabled. Fallback to fedora36.

Understood. We can revisit having a centos base in the future. Just having a well supported fedora base is good enough for now IMO.

**Comment by phlogistonjohn** [comment]
I will leave this open for roughly a day in case anyone else wants to chime in. Otherwise, anyone who can merge it should feel free to hit the merge button :-)

**Comment by anoopcs9** [comment]
> I tried to make it with `centos:stream9` but failed, even with `epel` repo enabled. Fallback to `fedora36`.

Just curious. Where did it fail?

**Comment by synarete** [comment]
> > I tried to make it with `centos:stream9` but failed, even with `epel` repo enabled. Fallback to `fedora36`.
> 
> Just curious. Where did it fail?

When trying to install the required python packages (`epel` enabled) I get `conflicting requests` errors. For example, if you try `dnf install python-tox`. In other cases, package is missing (e.g., `dnf install 'python3dist(setuptools-scm)'`). 

I assume it is all solvable; after all, fedora35 and centos-stream9 are not that far away. It simply require further investigation.

**Review by anoopcs9 — APPROVED** [review]
> > Just curious. Where did it fail?
> 
> When trying to install the required python packages (`epel` enabled) I get `conflicting requests` errors. For example, if you try `dnf install python-tox`. In other cases, package is missing (e.g., `dnf install 'python3dist(setuptools-scm)'`).
> 
> I assume it is all solvable; after all, fedora35 and centos-stream9 are not that far away. It simply require further investigation.

With CRB and EPEL repositories enabled `python-inotify_simple` is the only package missing for which I have [requested](https://bugzilla.redhat.com/show_bug.cgi?id=2122894) for making it available via EPEL.
```diff --git a/tests/container/Containerfile b/tests/container/Containerfile
index b6c3a5b..e8ea058 100644
--- a/tests/container/Containerfile
+++ b/tests/container/Containerfile
@@ -1,6 +1,8 @@
-FROM fedora:35
+FROM quay.io/centos/centos:stream9
 
-RUN yum install \
+RUN yum install -y epel-release epel-next-release
+
+RUN yum --enablerepo=crb install \
     -y --setopt=install_weak_deps=False \
     git \
     mercurial \
```

I hope we can switch to `stream9` soon.

**Comment by synarete** [comment]
> > > Just curious. Where did it fail?
> > 
> > 
> > When trying to install the required python packages (`epel` enabled) I get `conflicting requests` errors. For example, if you try `dnf install python-tox`. In other cases, package is missing (e.g., `dnf install 'python3dist(setuptools-scm)'`).
> > I assume it is all solvable; after all, fedora35 and centos-stream9 are not that far away. It simply require further investigation.
> 
> With CRB and EPEL repositories enabled `python-inotify_simple` is the only package missing for which I have [requested](https://bugzilla.redhat.com/show_bug.cgi?id=2122894) for making it available via EPEL.
> 
> ```diff
> index b6c3a5b..e8ea058 100644
> --- a/tests/container/Containerfile
> +++ b/tests/container/Containerfile
> @@ -1,6 +1,8 @@
> -FROM fedora:35
> +FROM quay.io/centos/centos:stream9
>  
> -RUN yum install \
> +RUN yum install -y epel-release epel-next-release
> +
> +RUN yum --enablerepo=crb install \
>      -y --setopt=install_weak_deps=False \
>      git \
>      mercurial \
> ```
> 
> I hope we can switch to `stream9` soon.



> > > Just curious. Where did it fail?
> > 
> > 
> > When trying to install the required python packages (`epel` enabled) I get `conflicting requests` errors. For example, if you try `dnf install python-tox`. In other cases, package is missing (e.g., `dnf install 'python3dist(setuptools-scm)'`).
> > I assume it is all solvable; after all, fedora35 and centos-stream9 are not that far away. It simply require further investigation.
> 
> With CRB and EPEL repositories enabled `python-inotify_simple` is the only package missing for which I have [requested](https://bugzilla.redhat.com/show_bug.cgi?id=2122894) for making it available via EPEL.
> 
> ```diff
> index b6c3a5b..e8ea058 100644
> --- a/tests/container/Containerfile
> +++ b/tests/container/Containerfile
> @@ -1,6 +1,8 @@
> -FROM fedora:35
> +FROM quay.io/centos/centos:stream9
>  
> -RUN yum install \
> +RUN yum install -y epel-release epel-next-release
> +
> +RUN yum --enablerepo=crb install \
>      -y --setopt=install_weak_deps=False \
>      git \
>      mercurial \
> ```
> 
> I hope we can switch to `stream9` soon.

@anoopcs9 Well done! many thanks for this info. Looks like I missed `epel-next-release`.

**Comment by phlogistonjohn** [comment]
@anoopcs9 could you please open an issue to track the dependency needed that's currently blocking the centos s9 switch? Thanks

**Pull request merged**
